### ISSUE TITLE
Algolia search?

### ISSUE THREAD

**Issue by mhillerstrom** [DaddyWarbucks/remote-docsify#3]
There is a plugin for __Docsify__ called [docsify-algolia-search-plugin](https://www.npmjs.com/package/docsify-algolia-search-plugin) which can intract with Algolia. Do you think it's worth the trouble tinkering with it in this context?

**Comment by DaddyWarbucks** [comment]
Hmmm. I think it goes against the core KISS concept of this idea if we had to deploy/configure Algolia. But I do think we should add the default search plugin (and any/all other plugins).

**Comment by mhillerstrom** [comment]
I agree - and it would probably just be overkill for `README.md`.
